
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Mismer All      <small><?= cclang('detail', ['Mismer All']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/mismer_all'); ?>">Mismer All</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Mismer All</h3>
                     <h5 class="widget-user-desc">Detail Mismer All</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_mismer_all" id="form_mismer_all" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ORG </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->ORG); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">MID </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->MID); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">MERCHANT DBA NAME </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->MERCHANT_DBA_NAME); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">STATUS EDC </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->STATUS_EDC); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">OPENDATE </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->OPENDATE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CITY </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->CITY); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">STATE </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->STATE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">DATE LAST MAINTAIN </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->DATE_LAST_MAINTAIN); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CONTACT PERSON </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->CONTACT_PERSON); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">TELP1 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->TELP1); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">TELP2 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->TELP2); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">MSO </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->MSO); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">MMO </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->MMO); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">DDA </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->DDA); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">MERCHANT TYPE </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->MERCHANT_TYPE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CHAIN STORE </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->CHAIN_STORE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SOURCE CODE </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->SOURCE_CODE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">MERCHANT NAME </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->MERCHANT_NAME); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ALAMAT1 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->ALAMAT1); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ALAMAT2 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->ALAMAT2); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">KOTA1 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->KOTA1); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">KOTA2 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->KOTA2); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ZIPCODE </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->ZIPCODE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom24 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom24); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">MCC1 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->MCC1); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">MCC2 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->MCC2); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom27 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom27); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom28 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom28); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom29 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom29); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">POS1 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->POS1); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">POS2 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->POS2); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">POS3 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->POS3); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">PLAN1 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->PLAN1); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">PLAN2 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->PLAN2); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">PLAN3 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->PLAN3); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">DATE LAST STATEMENT </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->DATE_LAST_STATEMENT); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom37 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom37); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom38 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom38); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom39 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom39); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom40 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom40); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom41 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom41); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom42 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom42); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom43 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom43); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom44 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom44); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom45 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom45); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom46 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom46); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom47 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom47); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NPWP </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->NPWP); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ACCOUNT NO </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->ACCOUNT_NO); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">BANK NAME </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->BANK_NAME); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom51 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom51); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom52 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom52); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom53 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom53); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom54 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom54); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom55 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom55); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom56 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom56); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom57 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom57); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom58 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom58); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">MDR VISA BNI </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->MDR_VISA_BNI); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom60 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom60); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom61 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom61); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom62 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom62); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom63 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom63); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom64 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom64); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kolom65 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->kolom65); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">MDR VISA OTHER </label>

                        <div class="col-sm-8">
                           <?= _ent($mismer_all->MDR_VISA_OTHER); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('mismer_all_update', function() use ($mismer_all){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit mismer_all (Ctrl+e)" href="<?= site_url('administrator/mismer_all/edit/'.$mismer_all->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Mismer All']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/mismer_all/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Mismer All']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
