
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      System Upload      <small><?= cclang('detail', ['System Upload']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/system_upload'); ?>">System Upload</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">System Upload</h3>
                     <h5 class="widget-user-desc">Detail System Upload</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_system_upload" id="form_system_upload" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($system_upload->id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Upload Date </label>

                        <div class="col-sm-8">
                           <?= _ent($system_upload->upload_date); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Upload Remark </label>

                        <div class="col-sm-8">
                           <?= _ent($system_upload->upload_remark); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Source </label>

                        <div class="col-sm-8">
                           <?= _ent($system_upload->source); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> File Path </label>
                        <div class="col-sm-8">
                             <?php if (is_image($system_upload->file_path)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/system_upload/' . $system_upload->file_path; ?>">
                                <img src="<?= BASE_URL . 'uploads/system_upload/' . $system_upload->file_path; ?>" class="image-responsive" alt="image system_upload" title="file_path system_upload" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/system_upload/' . $system_upload->file_path; ?>">
                                 <img src="<?= get_icon_file($system_upload->file_path); ?>" class="image-responsive" alt="image system_upload" title="file_path <?= $system_upload->file_path; ?>" width="40px"> 
                               <?= $system_upload->file_path ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">File Size </label>

                        <div class="col-sm-8">
                           <?= _ent($system_upload->file_size); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Row Data Count </label>

                        <div class="col-sm-8">
                           <?= _ent($system_upload->row_data_count); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Row Data Succeed </label>

                        <div class="col-sm-8">
                           <?= _ent($system_upload->row_data_succeed); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Row Data Failed </label>

                        <div class="col-sm-8">
                           <?= _ent($system_upload->row_data_failed); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Is Approved </label>

                        <div class="col-sm-8">
                           <?= _ent($system_upload->is_approved); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Upload At </label>

                        <div class="col-sm-8">
                           <?= _ent($system_upload->upload_at); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('system_upload_update', function() use ($system_upload){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit system_upload (Ctrl+e)" href="<?= site_url('administrator/system_upload/edit/'.$system_upload->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['System Upload']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/system_upload/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['System Upload']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
