
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      System Flpp      <small><?= cclang('detail', ['System Flpp']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/system_flpp'); ?>">System Flpp</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">System Flpp</h3>
                     <h5 class="widget-user-desc">Detail System Flpp</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_system_flpp" id="form_system_flpp" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NAMA PEMOHON </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->NAMA_PEMOHON); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">PEKERJAAN PEMOHON </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->PEKERJAAN_PEMOHON); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">JENIS KELAMIN </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->JENIS_KELAMIN); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NO KTP PEMOHON </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->NO_KTP_PEMOHON); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NPWP PEMOHON </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->NPWP_PEMOHON); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">GAJI POKOK </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->GAJI_POKOK); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NAMA PASANGAN </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->NAMA_PASANGAN); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NO KTP PASANGAN </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->NO_KTP_PASANGAN); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NO REKENING PEMOHON </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->NO_REKENING_PEMOHON); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">TGL AKAD </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->TGL_AKAD); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">HARGA RUMAH </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->HARGA_RUMAH); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NILAI KPR </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->NILAI_KPR); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SUKU BUNGA KPR </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->SUKU_BUNGA_KPR); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">TENOR </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->TENOR); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ANGSURAN KPR </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->ANGSURAN_KPR); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NILAI FLPP </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->NILAI_FLPP); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NAMA PENGEMBANG </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->NAMA_PENGEMBANG); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NAMA PERUMAHAN </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->NAMA_PERUMAHAN); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ALAMAT AGUNAN </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->ALAMAT_AGUNAN); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">KOTA AGUNAN </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->KOTA_AGUNAN); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">KODE POS AGUNAN </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->KODE_POS_AGUNAN); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">LUAS TANAH </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->LUAS_TANAH); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">LUAS BANGUNAN </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->LUAS_BANGUNAN); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Batch Id </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->batch_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Create Date </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->create_date); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Month </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->month); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Year </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->year); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Is Generate </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->is_generate); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ID </label>

                        <div class="col-sm-8">
                           <?= _ent($system_flpp->ID); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('system_flpp_update', function() use ($system_flpp){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit system_flpp (Ctrl+e)" href="<?= site_url('administrator/system_flpp/edit/'.$system_flpp->ID); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['System Flpp']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/system_flpp/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['System Flpp']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
