
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/System_flpp/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      System Flpp<small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">System XXXX</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">

      
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">





                        <?php is_allowed('system_flpp_add', function(){?>
                          <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="UPLOAD BATCH" href="<?=  site_url('administrator/system_flpp/upload_batch'); ?>">UPLOAD BATCH</a>
                          <!-- <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', ['System Flpp']); ?>  (Ctrl+a)" href="<?=  site_url('administrator/system_flpp/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', ['System Flpp']); ?></a> -->
                        <?php }) ?>


<!-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -->
<!-- <form action="<?php echo base_url(); ?>index.php/upload/import" method="post" name="upload_excel" enctype="multipart/form-data">
<table>
<tr>
	<td>Batch : <input type="text" name="batch_id" value="<?//=$batch_id;?>" ></td>	
	<td colspan='8'></td>

</tr>
</table>
<input type="file" name="file" id="file">
<button type="submit" id="submit" name="import" class="btn btn-primary button-loading">Import</button>
</form> -->

                        <?php is_allowed('system_flpp_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> System Flpp" href="<?= site_url('administrator/system_flpp/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('system_flpp_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf System Flpp" href="<?= site_url('administrator/system_flpp/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">System Flpp</h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', ['System Flpp']); ?>  <i class="label bg-yellow"><?= $system_flpp_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_system_flpp" id="form_system_flpp" action="<?= base_url('administrator/system_flpp/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                           <th>NAMA PEMOHON</th>
                           <!-- <th>PEKERJAAN PEMOHON</th>
                           <th>JENIS KELAMIN</th> -->
                           <th>NO KTP PEMOHON</th>
                           <!-- <th>NPWP PEMOHON</th>
                           <th>GAJI POKOK</th> -->
                           <!-- <th>NAMA PASANGAN</th>
                           <th>NO KTP PASANGAN</th> -->
                           <!-- <th>NO REKENING PEMOHON</th> -->
                           <th>TGL AKAD</th>
                           <th>HARGA RUMAH</th>
                           <th>NILAI KPR</th>
                           <th>SUKU BUNGA KPR</th>
                           <th>TENOR</th>
                           <th>ANGSURAN KPR</th>
                           <th>NILAI FLPP</th>
                           <!-- <th>NAMA PENGEMBANG</th>
                           <th>NAMA PERUMAHAN</th>
                           <th>ALAMAT AGUNAN</th>
                           <th>KOTA AGUNAN</th>
                           <th>KODE POS AGUNAN</th>
                           <th>LUAS TANAH</th>
                           <th>LUAS BANGUNAN</th> -->
                             <th>Batch Id</th>
                           <!-- 
                           <th>Create Date</th>
                           <th>Month</th>
                           <th>Year</th>
                           <th>Is Generate</th> -->
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_system_flpp">
                     <?php foreach($system_flpps as $system_flpp): ?>
                        <tr>
                           <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $system_flpp->ID; ?>">
                           </td>
                           
                           <td><?= _ent($system_flpp->NAMA_PEMOHON); ?></td> 
                           <!-- <td><?= _ent($system_flpp->PEKERJAAN_PEMOHON); ?></td> 
                           <td><?= _ent($system_flpp->JENIS_KELAMIN); ?></td>  -->
                             <td><?= _ent($system_flpp->NO_KTP_PEMOHON); ?></td> 
                           <!-- 
                           <td><?= _ent($system_flpp->NPWP_PEMOHON); ?></td> 
                           <td><?= _ent($system_flpp->GAJI_POKOK); ?></td>  -->
                           <!-- <td><?= _ent($system_flpp->NAMA_PASANGAN); ?></td> 
                           <td><?= _ent($system_flpp->NO_KTP_PASANGAN); ?></td>  -->
                           <!-- <td><?= _ent($system_flpp->NO_REKENING_PEMOHON); ?></td>  -->
                           <td><?= _ent($system_flpp->TGL_AKAD); ?></td> 
                           <td><?= _ent($system_flpp->HARGA_RUMAH); ?></td> 
                           <td><?= _ent($system_flpp->NILAI_KPR); ?></td> 
                           <td><?= _ent($system_flpp->SUKU_BUNGA_KPR); ?></td> 
                           <td><?= _ent($system_flpp->TENOR); ?></td> 
                           <td><?= _ent($system_flpp->ANGSURAN_KPR); ?></td> 
                           <td><?= _ent($system_flpp->NILAI_FLPP); ?></td> 
                           <!-- <td><?= _ent($system_flpp->NAMA_PENGEMBANG); ?></td> 
                           <td><?= _ent($system_flpp->NAMA_PERUMAHAN); ?></td> 
                           <td><?= _ent($system_flpp->ALAMAT_AGUNAN); ?></td> 
                           <td><?= _ent($system_flpp->KOTA_AGUNAN); ?></td> 
                           <td><?= _ent($system_flpp->KODE_POS_AGUNAN); ?></td> 
                           <td><?= _ent($system_flpp->LUAS_TANAH); ?></td> 
                           <td><?= _ent($system_flpp->LUAS_BANGUNAN); ?></td>  -->
                             <td><?= _ent($system_flpp->batch_id); ?></td> 
                           <!-- 
                           <td><?= _ent($system_flpp->create_date); ?></td> 
                           <td><?= _ent($system_flpp->month); ?></td> 
                           <td><?= _ent($system_flpp->year); ?></td> 
                           <td><?= _ent($system_flpp->is_generate); ?></td>  -->
                           <td width="200">

                           <!-- //  -->
                           <?php is_allowed('system_flpp_view', function() use ($system_flpp){?>
                              <a href="<?= site_url('administrator/system_flpp/get_detail_id/' . $system_flpp->NO_KTP_PEMOHON); ?>" class="btn btn-info">DETAIL TENOR</i> <?//= cclang('view_button'); ?>
                              <?php }) ?>


                           <!--  -->
                              <?php is_allowed('system_flpp_view', function() use ($system_flpp){?>
                              <a href="<?= site_url('administrator/system_flpp/view/' . $system_flpp->ID); ?>" class="btn btn-default">VIEW
                              <?php }) ?>
                              <?php is_allowed('system_flpp_update', function() use ($system_flpp){?>
                              <!-- <a href="<?= site_url('administrator/system_flpp/edit/' . $system_flpp->ID); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a> -->
                              <?php }) ?>
                              <!-- <?php is_allowed('system_flpp_delete', function() use ($system_flpp){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/system_flpp/delete/' . $system_flpp->ID); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?> -->
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($system_flpp_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           System Flpp data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                           <option value="generate">Generate</option>
                           <!-- <option value="delete">Delete</option> -->
                        </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'NAMA_PEMOHON' ? 'selected' :''; ?> value="NAMA_PEMOHON">NAMA PEMOHON</option>
                           <option <?= $this->input->get('f') == 'PEKERJAAN_PEMOHON' ? 'selected' :''; ?> value="PEKERJAAN_PEMOHON">PEKERJAAN PEMOHON</option>
                           <option <?= $this->input->get('f') == 'JENIS_KELAMIN' ? 'selected' :''; ?> value="JENIS_KELAMIN">JENIS KELAMIN</option>
                           <option <?= $this->input->get('f') == 'NO_KTP_PEMOHON' ? 'selected' :''; ?> value="NO_KTP_PEMOHON">NO KTP PEMOHON</option>
                           <option <?= $this->input->get('f') == 'NPWP_PEMOHON' ? 'selected' :''; ?> value="NPWP_PEMOHON">NPWP PEMOHON</option>
                           <option <?= $this->input->get('f') == 'GAJI_POKOK' ? 'selected' :''; ?> value="GAJI_POKOK">GAJI POKOK</option>
                           <option <?= $this->input->get('f') == 'NAMA_PASANGAN' ? 'selected' :''; ?> value="NAMA_PASANGAN">NAMA PASANGAN</option>
                           <option <?= $this->input->get('f') == 'NO_KTP_PASANGAN' ? 'selected' :''; ?> value="NO_KTP_PASANGAN">NO KTP PASANGAN</option>
                           <option <?= $this->input->get('f') == 'NO_REKENING_PEMOHON' ? 'selected' :''; ?> value="NO_REKENING_PEMOHON">NO REKENING PEMOHON</option>
                           <option <?= $this->input->get('f') == 'TGL_AKAD' ? 'selected' :''; ?> value="TGL_AKAD">TGL AKAD</option>
                           <option <?= $this->input->get('f') == 'HARGA_RUMAH' ? 'selected' :''; ?> value="HARGA_RUMAH">HARGA RUMAH</option>
                           <option <?= $this->input->get('f') == 'NILAI_KPR' ? 'selected' :''; ?> value="NILAI_KPR">NILAI KPR</option>
                           <option <?= $this->input->get('f') == 'SUKU_BUNGA_KPR' ? 'selected' :''; ?> value="SUKU_BUNGA_KPR">SUKU BUNGA KPR</option>
                           <option <?= $this->input->get('f') == 'TENOR' ? 'selected' :''; ?> value="TENOR">TENOR</option>
                           <option <?= $this->input->get('f') == 'ANGSURAN_KPR' ? 'selected' :''; ?> value="ANGSURAN_KPR">ANGSURAN KPR</option>
                           <option <?= $this->input->get('f') == 'NILAI_FLPP' ? 'selected' :''; ?> value="NILAI_FLPP">NILAI FLPP</option>
                           <option <?= $this->input->get('f') == 'NAMA_PENGEMBANG' ? 'selected' :''; ?> value="NAMA_PENGEMBANG">NAMA PENGEMBANG</option>
                           <option <?= $this->input->get('f') == 'NAMA_PERUMAHAN' ? 'selected' :''; ?> value="NAMA_PERUMAHAN">NAMA PERUMAHAN</option>
                           <option <?= $this->input->get('f') == 'ALAMAT_AGUNAN' ? 'selected' :''; ?> value="ALAMAT_AGUNAN">ALAMAT AGUNAN</option>
                           <option <?= $this->input->get('f') == 'KOTA_AGUNAN' ? 'selected' :''; ?> value="KOTA_AGUNAN">KOTA AGUNAN</option>
                           <option <?= $this->input->get('f') == 'KODE_POS_AGUNAN' ? 'selected' :''; ?> value="KODE_POS_AGUNAN">KODE POS AGUNAN</option>
                           <option <?= $this->input->get('f') == 'LUAS_TANAH' ? 'selected' :''; ?> value="LUAS_TANAH">LUAS TANAH</option>
                           <option <?= $this->input->get('f') == 'LUAS_BANGUNAN' ? 'selected' :''; ?> value="LUAS_BANGUNAN">LUAS BANGUNAN</option>
                           <option <?= $this->input->get('f') == 'batch_id' ? 'selected' :''; ?> value="batch_id">Batch Id</option>
                           <option <?= $this->input->get('f') == 'create_date' ? 'selected' :''; ?> value="create_date">Create Date</option>
                           <option <?= $this->input->get('f') == 'month' ? 'selected' :''; ?> value="month">Month</option>
                           <option <?= $this->input->get('f') == 'year' ? 'selected' :''; ?> value="year">Year</option>
                           <option <?= $this->input->get('f') == 'is_generate' ? 'selected' :''; ?> value="is_generate">Is Generate</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/system_flpp');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_system_flpp').serialize();
// ================
      if (bulk.val() == 'generate') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "Generate Data",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes",
            cancelButtonText: "No",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/system_flpp/generate?' + serialize_bulk;      
            }
          });

        return false;

      } 
      //======================================================== 
      else if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/system_flpp/delete?' + serialize_bulk;      
            }
          });

        return false;

      }else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>