
select count(*) from temp_upload_mismer where IS_MATCH=1;
select count(*) from temp_upload_mismer where IS_MATCH=0;
select * from temp_upload_mismer ;

truncate temp_upload_mismer;

LOAD DATA INFILE 'C:/xampp/htdocs/mattools/uploads/system_upload/2-MISMER.csv' 
INTO TABLE temp_upload_mismer
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
 IGNORE 1 ROWS
(MID,MERCHAN_DBA_NAME,STATUS_EDC,@OPEN_DATE,MSO,SOURCE_CODE,POS1,IS_MATCH,BatchID,ID)
SET OPEN_DATE = STR_TO_DATE(@OPEN_DATE, '%m/%d/%Y')

-- -----????????????
, IS_MATCH = 
CASE

	WHEN LEFT(MSO,1)='A' THEN 1
	WHEN LEFT(MSO,1)='B' THEN 1
	WHEN LEFT(MSO,1)='C' THEN 1
	WHEN LEFT(MSO,1)='D' THEN 1
	WHEN LEFT(MSO,1)='E' THEN 1
	WHEN LEFT(MSO,1)='F' THEN 1
	WHEN LEFT(MSO,1)='G' THEN 1
	WHEN LEFT(MSO,1)='H' THEN 1
	WHEN LEFT(MSO,1)='I' THEN 1
	WHEN LEFT(MSO,1)='J' THEN 1
	WHEN LEFT(MSO,1)='K' THEN 1
	WHEN LEFT(MSO,1)='L' THEN 1
	WHEN LEFT(MSO,1)='M' THEN 1
	WHEN LEFT(MSO,1)='N' THEN 1
	WHEN LEFT(MSO,1)='O' THEN 1
	WHEN LEFT(MSO,1)='R' THEN 1
	WHEN LEFT(MSO,1)='S' THEN 1
    
	WHEN SUBSTRING(MID,2,2)='01' THEN 1
	WHEN SUBSTRING(MID,2,2)='02' THEN 1
	WHEN SUBSTRING(MID,2,2)='03' THEN 1
	WHEN SUBSTRING(MID,2,2)='04' THEN 1
	WHEN SUBSTRING(MID,2,2)='05' THEN 1
	WHEN SUBSTRING(MID,2,2)='06' THEN 1
	WHEN SUBSTRING(MID,2,2)='07' THEN 1
	WHEN SUBSTRING(MID,2,2)='08' THEN 1
	WHEN SUBSTRING(MID,2,2)='09' THEN 1
	WHEN SUBSTRING(MID,2,2)='10' THEN 1
	WHEN SUBSTRING(MID,2,2)='11' THEN 1
	WHEN SUBSTRING(MID,2,2)='12' THEN 1
	WHEN SUBSTRING(MID,2,2)='14' THEN 1
	WHEN SUBSTRING(MID,2,2)='15' THEN 1
	WHEN SUBSTRING(MID,2,2)='16' THEN 1
	WHEN SUBSTRING(MID,2,2)='17' THEN 1
	WHEN SUBSTRING(MID,2,2)='18' THEN 1    
    
  	ELSE 0
END



;



-- ===================
INSERT INTO mismer_detail

SELECT 
NULL RowID,
-- (SELECT max(BatchID) as BatchID FROM systemupload WHERE ApplicationSource='MISMER') BatchID, -- !!!
999 BatchID, -- dev

--  date_format(str_to_date(a.OPEN_DATE,'%m/%d/%Y'),'%Y/%m/%d')
-- AS OPEN_DATE , 

a.OPEN_DATE,
a.MID,
a.MERCHAN_DBA_NAME,
a.STATUS_EDC,
a.MSO,
a.SOURCE_CODE,

CASE
	WHEN a.POS1 <= 100 THEN 1
	ELSE LEFT(a.POS1,1)
END
AS
POS1,

CASE
	WHEN LEFT(a.MSO,1)='A' THEN 'WMD'
	WHEN LEFT(a.MSO,1)='B' THEN 'WPD'
	WHEN LEFT(a.MSO,1)='C' THEN 'WPL'
	WHEN LEFT(a.MSO,1)='D' THEN 'WBN'
	WHEN LEFT(a.MSO,1)='E' THEN 'WSM'
	WHEN LEFT(a.MSO,1)='F' THEN 'WSY'
	WHEN LEFT(a.MSO,1)='G' THEN 'WMK'
	WHEN LEFT(a.MSO,1)='H' THEN 'WDR'
	WHEN LEFT(a.MSO,1)='I' THEN 'WBJ'
	WHEN LEFT(a.MSO,1)='J' THEN 'WMO'
	WHEN LEFT(a.MSO,1)='K' THEN 'WPU'
	WHEN LEFT(a.MSO,1)='L' THEN 'WJS'
	WHEN LEFT(a.MSO,1)='M' THEN 'WJK'
	WHEN LEFT(a.MSO,1)='N' THEN 'WJB'
	WHEN LEFT(a.MSO,1)='O' THEN 'WJY'
	WHEN LEFT(a.MSO,1)='R' THEN 'WYK'
	WHEN LEFT(a.MSO,1)='S' THEN 'WMA'	
    
	WHEN SUBSTRING(a.MID,2,2)='01' THEN 'WMD'
	WHEN SUBSTRING(a.MID,2,2)='02' THEN 'WPD'
	WHEN SUBSTRING(a.MID,2,2)='03' THEN 'WPL'
	WHEN SUBSTRING(a.MID,2,2)='04' THEN 'WBN'
	WHEN SUBSTRING(a.MID,2,2)='05' THEN 'WSM'
	WHEN SUBSTRING(a.MID,2,2)='06' THEN 'WSY'
	WHEN SUBSTRING(a.MID,2,2)='07' THEN 'WMK'
	WHEN SUBSTRING(a.MID,2,2)='08' THEN 'WDR'
	WHEN SUBSTRING(a.MID,2,2)='09' THEN 'WBJ'
	WHEN SUBSTRING(a.MID,2,2)='10' THEN 'WJS'
	WHEN SUBSTRING(a.MID,2,2)='11' THEN 'WMO'
	WHEN SUBSTRING(a.MID,2,2)='12' THEN 'WJK'
	WHEN SUBSTRING(a.MID,2,2)='14' THEN 'WJB'
	WHEN SUBSTRING(a.MID,2,2)='15' THEN 'WJY'
	WHEN SUBSTRING(a.MID,2,2)='16' THEN 'WPU'
	WHEN SUBSTRING(a.MID,2,2)='17' THEN 'WYK'
	WHEN SUBSTRING(a.MID,2,2)='18' THEN 'WMA'    
    
-- 	WHEN LEFT(a.MSO,1)='' THEN 'BLANK'
  	ELSE NULL
END

as WILAYAH,
mc.Channel as CHANNEL,
  
 CASE

	WHEN LEFT(a.MID,1)='3'  THEN 'YAP'
  	ELSE 'EDC'
END
as TYPE_MID
,NULL IS_MATCH
,null create_at
,null update_at


FROM temp_upload_mismer a 
LEFT JOIN mso_channel mc ON a.MSO=mc.MSO

-- WHERE a.ID =??? -- IN(select ID from templateuploadmismer)
-- AND IS_VALID=1

;

select * from mismer_detail


