
select count(*) from temp_upload_mismer where IS_MATCH=1;

truncate temp_upload_mismer;

LOAD DATA INFILE 'C:/xampp/htdocs/mattools/uploads/system_upload/2-MISMER.csv' 
INTO TABLE temp_upload_mismer
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
 IGNORE 1 ROWS
(MID,MERCHAN_DBA_NAME,STATUS_EDC,@OPEN_DATE,MSO,SOURCE_CODE,POS1,IS_MATCH,BatchID,ID)
SET OPEN_DATE = STR_TO_DATE(@OPEN_DATE, '%m/%d/%Y')
, IS_MATCH = 
CASE

	WHEN LEFT(MSO,1)='A' THEN 1
	WHEN LEFT(MSO,1)='B' THEN 1
	WHEN LEFT(MSO,1)='C' THEN 1
	WHEN LEFT(MSO,1)='D' THEN 1
	WHEN LEFT(MSO,1)='E' THEN 1
	WHEN LEFT(MSO,1)='F' THEN 1
	WHEN LEFT(MSO,1)='G' THEN 1
	WHEN LEFT(MSO,1)='H' THEN 1
	WHEN LEFT(MSO,1)='I' THEN 1
	WHEN LEFT(MSO,1)='J' THEN 1
	WHEN LEFT(MSO,1)='K' THEN 1
	WHEN LEFT(MSO,1)='L' THEN 1
	WHEN LEFT(MSO,1)='M' THEN 1
	WHEN LEFT(MSO,1)='N' THEN 1
	WHEN LEFT(MSO,1)='O' THEN 1
	WHEN LEFT(MSO,1)='R' THEN 1
	WHEN LEFT(MSO,1)='S' THEN 1
    
	WHEN SUBSTRING(MID,2,2)='01' THEN 1
	WHEN SUBSTRING(MID,2,2)='02' THEN 1
	WHEN SUBSTRING(MID,2,2)='03' THEN 1
	WHEN SUBSTRING(MID,2,2)='04' THEN 1
	WHEN SUBSTRING(MID,2,2)='05' THEN 1
	WHEN SUBSTRING(MID,2,2)='06' THEN 1
	WHEN SUBSTRING(MID,2,2)='07' THEN 1
	WHEN SUBSTRING(MID,2,2)='08' THEN 1
	WHEN SUBSTRING(MID,2,2)='09' THEN 1
	WHEN SUBSTRING(MID,2,2)='10' THEN 1
	WHEN SUBSTRING(MID,2,2)='11' THEN 1
	WHEN SUBSTRING(MID,2,2)='12' THEN 1
	WHEN SUBSTRING(MID,2,2)='14' THEN 1
	WHEN SUBSTRING(MID,2,2)='15' THEN 1
	WHEN SUBSTRING(MID,2,2)='16' THEN 1
	WHEN SUBSTRING(MID,2,2)='17' THEN 1
	WHEN SUBSTRING(MID,2,2)='18' THEN 1    
    
  	ELSE 0
END



;
