drop table mismer_detail
select * from mismer_detail

CREATE TABLE `mismer_detail` (
  `RowID` int(11) unsigned NOT NULL,
  `BatchID` int(11) NOT NULL,
  `OPEN_DATE` date NOT NULL,
  `MID` int(50) NOT NULL,
  `MERCHAN_DBA_NAME` varchar(255) DEFAULT NULL,
  `STATUS_EDC` varchar(100) DEFAULT NULL,
  `MSO` varchar(100) DEFAULT NULL,
  `SOURCE_CODE` varchar(255) DEFAULT NULL,
  `POS1` varchar(100) DEFAULT NULL,
  `WILAYAH` varchar(100) DEFAULT NULL,
  `CHANNEL` varchar(100) DEFAULT NULL,
  `TYPE_MID` varchar(50) NOT NULL,
  `IS_MATCH` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`MID`)
) ENGINE=InnoDB AUTO_INCREMENT=358961 DEFAULT CHARSET=utf8



select * from temp_upload_tes

-- =============
truncate temp_upload_tes;

LOAD DATA INFILE 'C:/xampp/htdocs/mattools/uploads/system_upload/2-MISMER.csv' 
INTO TABLE temp_upload_tes
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
 IGNORE 1 ROWS
(MID,MERCHAN_DBA_NAME,STATUS_EDC,@OPEN_DATE,MSO,SOURCE_CODE,@POS1,@WILAYAH,CHANNEL,TYPE_MID,IS_MATCH,id)

SET 
-- convert date mdy to YMD
OPEN_DATE = STR_TO_DATE(@OPEN_DATE, '%m/%d/%Y')
-- POST1 format
,POS1 = 
CASE
	WHEN @POS1 <= 100 THEN 1
	ELSE LEFT(@POS1,1)
END
-- WILAYAH
, WILAYAH = 
CASE
	WHEN LEFT(@MSO,1)='A' THEN 'WMD'
    ELSE NULL
END

CASE
	WHEN LEFT(@MSO,1)='A' THEN 'WMD'
	WHEN LEFT(@MSO,1)='B' THEN 'WPD'
	WHEN LEFT(@MSO,1)='C' THEN 'WPL'
	WHEN LEFT(@MSO,1)='D' THEN 'WBN'
	WHEN LEFT(@MSO,1)='E' THEN 'WSM'
	WHEN LEFT(@MSO,1)='F' THEN 'WSY'
	WHEN LEFT(@MSO,1)='G' THEN 'WMK'
	WHEN LEFT(@MSO,1)='H' THEN 'WDR'
	WHEN LEFT(@MSO,1)='I' THEN 'WBJ'
	WHEN LEFT(@MSO,1)='J' THEN 'WMO'
	WHEN LEFT(@MSO,1)='K' THEN 'WPU'
	WHEN LEFT(@MSO,1)='L' THEN 'WJS'
	WHEN LEFT(@MSO,1)='M' THEN 'WJK'
	WHEN LEFT(@MSO,1)='N' THEN 'WJB'
	WHEN LEFT(@MSO,1)='O' THEN 'WJY'
	WHEN LEFT(@MSO,1)='R' THEN 'WYK'
	WHEN LEFT(@MSO,1)='S' THEN 'WMA'	
    
	WHEN SUBSTRING(a.MID,2,2)='01' THEN 'WMD'
	WHEN SUBSTRING(a.MID,2,2)='02' THEN 'WPD'
	WHEN SUBSTRING(a.MID,2,2)='03' THEN 'WPL'
	WHEN SUBSTRING(a.MID,2,2)='04' THEN 'WBN'
	WHEN SUBSTRING(a.MID,2,2)='05' THEN 'WSM'
	WHEN SUBSTRING(a.MID,2,2)='06' THEN 'WSY'
	WHEN SUBSTRING(a.MID,2,2)='07' THEN 'WMK'
	WHEN SUBSTRING(a.MID,2,2)='08' THEN 'WDR'
	WHEN SUBSTRING(a.MID,2,2)='09' THEN 'WBJ'
	WHEN SUBSTRING(a.MID,2,2)='10' THEN 'WJS'
	WHEN SUBSTRING(a.MID,2,2)='11' THEN 'WMO'
	WHEN SUBSTRING(a.MID,2,2)='12' THEN 'WJK'
	WHEN SUBSTRING(a.MID,2,2)='14' THEN 'WJB'
	WHEN SUBSTRING(a.MID,2,2)='15' THEN 'WJY'
	WHEN SUBSTRING(a.MID,2,2)='16' THEN 'WPU'
	WHEN SUBSTRING(a.MID,2,2)='17' THEN 'WYK'
	WHEN SUBSTRING(a.MID,2,2)='18' THEN 'WMA'    
    
-- 	WHEN LEFT(@MSO,1)='' THEN 'BLANK'
  	ELSE NULL
END

;
-- ==========





CREATE TABLE `temp_upload_tes` (
  `MID` varchar(100) DEFAULT NULL,
  `MERCHAN_DBA_NAME` varchar(255) DEFAULT NULL,
  `STATUS_EDC` varchar(100) DEFAULT NULL,
  `OPEN_DATE` date NOT NULL,
  `MSO` varchar(100) DEFAULT NULL,
  `SOURCE_CODE` varchar(255) DEFAULT NULL,
  `POS1` varchar(100) DEFAULT NULL,
  
 `WILAYAH` varchar(100) DEFAULT NULL,
  `CHANNEL` varchar(100) DEFAULT NULL,
  `TYPE_MID` varchar(50) NOT NULL,
  `IS_MATCH` int(11) NOT NULL,
  
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL,  
  
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=393211 DEFAULT CHARSET=utf8

-- =============

drop table mismer_unmatch
select * from mismer_unmatch
CREATE TABLE `mismer_unmatch` (
  `RowID` int(11) unsigned NOT NULL ,
  `BatchID` int(11) NOT NULL,
  `OPEN_DATE` date NOT NULL,
  `MID` int(50) NOT NULL,
  `MERCHAN_DBA_NAME` varchar(255) DEFAULT NULL,
  `STATUS_EDC` varchar(100) DEFAULT NULL,
  `MSO` varchar(100) DEFAULT NULL,
  `SOURCE_CODE` varchar(255) DEFAULT NULL,
  `POS1` varchar(100) DEFAULT NULL,
  `WILAYAH` varchar(100) DEFAULT NULL,
  `CHANNEL` varchar(100) DEFAULT NULL,
  `TYPE_MID` varchar(100) DEFAULT NULL,
  `IS_UPDATE` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`MID`)
) ENGINE=InnoDB AUTO_INCREMENT=358961 DEFAULT CHARSET=utf8